# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-10 03:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_auto_20171110_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='WxImg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='img')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RenameModel(
            old_name='IMG',
            new_name='AliImg',
        ),
    ]
