# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-11-10 05:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_auto_20171110_0330'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AliImg',
            new_name='Img',
        ),
        migrations.DeleteModel(
            name='WxImg',
        ),
    ]
